FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:14

WORKDIR /workspace


RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1

RUN npm install -g @nestjs/cli