export enum ReelStatus {
  UPLOAD_SUBMITTED = 'UPLOAD_SUBMITTED',
  UPLOAD_IN_PROGRESS = 'UPLOAD_IN_PROGRESS',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  NEEDS_CHANGES = 'NEEDS_CHANGES',
}
