name: Docker Image CI

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Deploy lambda
       run: >
        echo "$github.ref_type"
        echo "$github.ref_name"
        echo "$github.ref"
       
     - name: Deploy stg lambda
       if: ${{ github.ref_type == 'branch' && github.ref_name == 'master' }}
       run: echo '2'
       
     - name: Deploy stg lambda
       if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v')  }}
       run: echo '3'
